# coding: utf-8

"""
    Störning

    Störningsinformation för realtid och planerad trafik  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from pyvasttrafik.api.configuration import Configuration


class MunicipalityApiModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'municipality_number': 'int',
        'municipality_name': 'str'
    }

    attribute_map = {
        'municipality_number': 'municipalityNumber',
        'municipality_name': 'municipalityName'
    }

    def __init__(self, municipality_number=None, municipality_name=None, local_vars_configuration=None):  # noqa: E501
        """MunicipalityApiModel - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._municipality_number = None
        self._municipality_name = None
        self.discriminator = None

        if municipality_number is not None:
            self.municipality_number = municipality_number
        if municipality_name is not None:
            self.municipality_name = municipality_name

    @property
    def municipality_number(self):
        """Gets the municipality_number of this MunicipalityApiModel.  # noqa: E501

        Example data: 1480  # noqa: E501

        :return: The municipality_number of this MunicipalityApiModel.  # noqa: E501
        :rtype: int
        """
        return self._municipality_number

    @municipality_number.setter
    def municipality_number(self, municipality_number):
        """Sets the municipality_number of this MunicipalityApiModel.

        Example data: 1480  # noqa: E501

        :param municipality_number: The municipality_number of this MunicipalityApiModel.  # noqa: E501
        :type municipality_number: int
        """

        self._municipality_number = municipality_number

    @property
    def municipality_name(self):
        """Gets the municipality_name of this MunicipalityApiModel.  # noqa: E501

        Example data: \"GÃ¶teborg\"  # noqa: E501

        :return: The municipality_name of this MunicipalityApiModel.  # noqa: E501
        :rtype: str
        """
        return self._municipality_name

    @municipality_name.setter
    def municipality_name(self, municipality_name):
        """Sets the municipality_name of this MunicipalityApiModel.

        Example data: \"GÃ¶teborg\"  # noqa: E501

        :param municipality_name: The municipality_name of this MunicipalityApiModel.  # noqa: E501
        :type municipality_name: str
        """

        self._municipality_name = municipality_name

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MunicipalityApiModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MunicipalityApiModel):
            return True

        return self.to_dict() != other.to_dict()
