# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik  # noqa: E501

    The version of the OpenAPI document: v4
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from pyvasttrafik.api.configuration import Configuration


class VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'gid': 'str',
        'name': 'str',
        'number': 'int',
        'short_name': 'str'
    }

    attribute_map = {
        'gid': 'gid',
        'name': 'name',
        'number': 'number',
        'short_name': 'shortName'
    }

    def __init__(self, gid=None, name=None, number=None, short_name=None, local_vars_configuration=None):  # noqa: E501
        """VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._gid = None
        self._name = None
        self._number = None
        self._short_name = None
        self.discriminator = None

        self.gid = gid
        self.name = name
        if number is not None:
            self.number = number
        self.short_name = short_name

    @property
    def gid(self):
        """Gets the gid of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.  # noqa: E501

        The 16-digit Västtrafik gid of the tariff zone.  # noqa: E501

        :return: The gid of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.  # noqa: E501
        :rtype: str
        """
        return self._gid

    @gid.setter
    def gid(self, gid):
        """Sets the gid of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.

        The 16-digit Västtrafik gid of the tariff zone.  # noqa: E501

        :param gid: The gid of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.  # noqa: E501
        :type gid: str
        """

        self._gid = gid

    @property
    def name(self):
        """Gets the name of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.  # noqa: E501

        The name of the tariff zone.  # noqa: E501

        :return: The name of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.

        The name of the tariff zone.  # noqa: E501

        :param name: The name of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def number(self):
        """Gets the number of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.  # noqa: E501

        The tariff zone number.  # noqa: E501

        :return: The number of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.

        The tariff zone number.  # noqa: E501

        :param number: The number of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.  # noqa: E501
        :type number: int
        """

        self._number = number

    @property
    def short_name(self):
        """Gets the short_name of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.  # noqa: E501

        The short name of the tariff zone.  # noqa: E501

        :return: The short_name of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.  # noqa: E501
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """Sets the short_name of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.

        The short name of the tariff zone.  # noqa: E501

        :param short_name: The short_name of this VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel.  # noqa: E501
        :type short_name: str
        """

        self._short_name = short_name

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel):
            return True

        return self.to_dict() != other.to_dict()
