# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik  # noqa: E501

    The version of the OpenAPI document: v4
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from pyvasttrafik.api.configuration import Configuration


class VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'results': 'list[VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel]',
        'pagination': 'VTApiPlaneraResaWebV4ModelsPaginationProperties',
        'links': 'VTApiPlaneraResaWebV4ModelsPaginationLinks'
    }

    attribute_map = {
        'results': 'results',
        'pagination': 'pagination',
        'links': 'links'
    }

    def __init__(self, results=None, pagination=None, links=None, local_vars_configuration=None):  # noqa: E501
        """VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._results = None
        self._pagination = None
        self._links = None
        self.discriminator = None

        self.results = results
        if pagination is not None:
            self.pagination = pagination
        if links is not None:
            self.links = links

    @property
    def results(self):
        """Gets the results of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse.  # noqa: E501

        The results.  # noqa: E501

        :return: The results of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse.  # noqa: E501
        :rtype: list[VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse.

        The results.  # noqa: E501

        :param results: The results of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse.  # noqa: E501
        :type results: list[VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel]
        """

        self._results = results

    @property
    def pagination(self):
        """Gets the pagination of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse.  # noqa: E501


        :return: The pagination of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse.  # noqa: E501
        :rtype: VTApiPlaneraResaWebV4ModelsPaginationProperties
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse.


        :param pagination: The pagination of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse.  # noqa: E501
        :type pagination: VTApiPlaneraResaWebV4ModelsPaginationProperties
        """

        self._pagination = pagination

    @property
    def links(self):
        """Gets the links of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse.  # noqa: E501


        :return: The links of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse.  # noqa: E501
        :rtype: VTApiPlaneraResaWebV4ModelsPaginationLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse.


        :param links: The links of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse.  # noqa: E501
        :type links: VTApiPlaneraResaWebV4ModelsPaginationLinks
        """

        self._links = links

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse):
            return True

        return self.to_dict() != other.to_dict()
