# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik  # noqa: E501

    The version of the OpenAPI document: v4
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from pyvasttrafik.api.configuration import Configuration


class VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'gid': 'str',
        'name': 'str',
        'latitude': 'float',
        'longitude': 'float',
        'tariff_zone1': 'VTApiPlaneraResaWebV4ModelsJourneysTariffZoneApiModel',
        'tariff_zone2': 'VTApiPlaneraResaWebV4ModelsJourneysTariffZoneApiModel'
    }

    attribute_map = {
        'gid': 'gid',
        'name': 'name',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'tariff_zone1': 'tariffZone1',
        'tariff_zone2': 'tariffZone2'
    }

    def __init__(self, gid=None, name=None, latitude=None, longitude=None, tariff_zone1=None, tariff_zone2=None, local_vars_configuration=None):  # noqa: E501
        """VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._gid = None
        self._name = None
        self._latitude = None
        self._longitude = None
        self._tariff_zone1 = None
        self._tariff_zone2 = None
        self.discriminator = None

        self.gid = gid
        self.name = name
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if tariff_zone1 is not None:
            self.tariff_zone1 = tariff_zone1
        if tariff_zone2 is not None:
            self.tariff_zone2 = tariff_zone2

    @property
    def gid(self):
        """Gets the gid of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501

        The 16-digit Västtrafik gid of the stop area.  # noqa: E501

        :return: The gid of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501
        :rtype: str
        """
        return self._gid

    @gid.setter
    def gid(self, gid):
        """Sets the gid of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.

        The 16-digit Västtrafik gid of the stop area.  # noqa: E501

        :param gid: The gid of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501
        :type gid: str
        """

        self._gid = gid

    @property
    def name(self):
        """Gets the name of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501

        The stop area name.  # noqa: E501

        :return: The name of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.

        The stop area name.  # noqa: E501

        :param name: The name of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def latitude(self):
        """Gets the latitude of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501

        The latitude of the stop point.  # noqa: E501

        :return: The latitude of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.

        The latitude of the stop point.  # noqa: E501

        :param latitude: The latitude of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501
        :type latitude: float
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501

        The longitude of the stop point.  # noqa: E501

        :return: The longitude of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.

        The longitude of the stop point.  # noqa: E501

        :param longitude: The longitude of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501
        :type longitude: float
        """

        self._longitude = longitude

    @property
    def tariff_zone1(self):
        """Gets the tariff_zone1 of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501


        :return: The tariff_zone1 of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501
        :rtype: VTApiPlaneraResaWebV4ModelsJourneysTariffZoneApiModel
        """
        return self._tariff_zone1

    @tariff_zone1.setter
    def tariff_zone1(self, tariff_zone1):
        """Sets the tariff_zone1 of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.


        :param tariff_zone1: The tariff_zone1 of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501
        :type tariff_zone1: VTApiPlaneraResaWebV4ModelsJourneysTariffZoneApiModel
        """

        self._tariff_zone1 = tariff_zone1

    @property
    def tariff_zone2(self):
        """Gets the tariff_zone2 of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501


        :return: The tariff_zone2 of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501
        :rtype: VTApiPlaneraResaWebV4ModelsJourneysTariffZoneApiModel
        """
        return self._tariff_zone2

    @tariff_zone2.setter
    def tariff_zone2(self, tariff_zone2):
        """Sets the tariff_zone2 of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.


        :param tariff_zone2: The tariff_zone2 of this VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel.  # noqa: E501
        :type tariff_zone2: VTApiPlaneraResaWebV4ModelsJourneysTariffZoneApiModel
        """

        self._tariff_zone2 = tariff_zone2

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VTApiPlaneraResaWebV4ModelsJourneysStopAreaApiModel):
            return True

        return self.to_dict() != other.to_dict()
