# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik  # noqa: E501

    The version of the OpenAPI document: v4
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from pyvasttrafik.api.configuration import Configuration


class VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'gid': 'str',
        'name': 'str',
        'platform': 'str',
        'latitude': 'float',
        'longitude': 'float',
        'stop_area': 'VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel'
    }

    attribute_map = {
        'gid': 'gid',
        'name': 'name',
        'platform': 'platform',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'stop_area': 'stopArea'
    }

    def __init__(self, gid=None, name=None, platform=None, latitude=None, longitude=None, stop_area=None, local_vars_configuration=None):  # noqa: E501
        """VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._gid = None
        self._name = None
        self._platform = None
        self._latitude = None
        self._longitude = None
        self._stop_area = None
        self.discriminator = None

        self.gid = gid
        self.name = name
        self.platform = platform
        self.latitude = latitude
        self.longitude = longitude
        if stop_area is not None:
            self.stop_area = stop_area

    @property
    def gid(self):
        """Gets the gid of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501

        The 16-digit Västtrafik gid of the stop point.  # noqa: E501

        :return: The gid of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501
        :rtype: str
        """
        return self._gid

    @gid.setter
    def gid(self, gid):
        """Sets the gid of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.

        The 16-digit Västtrafik gid of the stop point.  # noqa: E501

        :param gid: The gid of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501
        :type gid: str
        """
        if self.local_vars_configuration.client_side_validation and gid is None:  # noqa: E501
            raise ValueError("Invalid value for `gid`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                gid is not None and len(gid) < 1):
            raise ValueError("Invalid value for `gid`, length must be greater than or equal to `1`")  # noqa: E501

        self._gid = gid

    @property
    def name(self):
        """Gets the name of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501

        The stop point name.  # noqa: E501

        :return: The name of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.

        The stop point name.  # noqa: E501

        :param name: The name of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501
        :type name: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def platform(self):
        """Gets the platform of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501

        The platform of the stop point.  # noqa: E501

        :return: The platform of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501
        :rtype: str
        """
        return self._platform

    @platform.setter
    def platform(self, platform):
        """Sets the platform of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.

        The platform of the stop point.  # noqa: E501

        :param platform: The platform of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501
        :type platform: str
        """

        self._platform = platform

    @property
    def latitude(self):
        """Gets the latitude of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501

        The latitude coordinate of the stop point.  # noqa: E501

        :return: The latitude of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.

        The latitude coordinate of the stop point.  # noqa: E501

        :param latitude: The latitude of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501
        :type latitude: float
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501

        The longitude coordinate of the stop point.  # noqa: E501

        :return: The longitude of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.

        The longitude coordinate of the stop point.  # noqa: E501

        :param longitude: The longitude of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501
        :type longitude: float
        """

        self._longitude = longitude

    @property
    def stop_area(self):
        """Gets the stop_area of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501


        :return: The stop_area of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501
        :rtype: VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel
        """
        return self._stop_area

    @stop_area.setter
    def stop_area(self, stop_area):
        """Sets the stop_area of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.


        :param stop_area: The stop_area of this VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel.  # noqa: E501
        :type stop_area: VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel
        """

        self._stop_area = stop_area

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel):
            return True

        return self.to_dict() != other.to_dict()
