# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik  # noqa: E501

    The version of the OpenAPI document: v4
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from pyvasttrafik.api.configuration import Configuration


class VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'gid': 'str',
        'direction': 'str',
        'number': 'str',
        'line': 'VTApiPlaneraResaWebV4ModelsJourneysLineApiModel'
    }

    attribute_map = {
        'gid': 'gid',
        'direction': 'direction',
        'number': 'number',
        'line': 'line'
    }

    def __init__(self, gid=None, direction=None, number=None, line=None, local_vars_configuration=None):  # noqa: E501
        """VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._gid = None
        self._direction = None
        self._number = None
        self._line = None
        self.discriminator = None

        self.gid = gid
        self.direction = direction
        self.number = number
        if line is not None:
            self.line = line

    @property
    def gid(self):
        """Gets the gid of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.  # noqa: E501

        16-digit Västtrafik service journey gid.  # noqa: E501

        :return: The gid of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.  # noqa: E501
        :rtype: str
        """
        return self._gid

    @gid.setter
    def gid(self, gid):
        """Sets the gid of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.

        16-digit Västtrafik service journey gid.  # noqa: E501

        :param gid: The gid of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.  # noqa: E501
        :type gid: str
        """
        if self.local_vars_configuration.client_side_validation and gid is None:  # noqa: E501
            raise ValueError("Invalid value for `gid`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                gid is not None and len(gid) < 1):
            raise ValueError("Invalid value for `gid`, length must be greater than or equal to `1`")  # noqa: E501

        self._gid = gid

    @property
    def direction(self):
        """Gets the direction of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.  # noqa: E501

        A description of the direction.  # noqa: E501

        :return: The direction of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.  # noqa: E501
        :rtype: str
        """
        return self._direction

    @direction.setter
    def direction(self, direction):
        """Sets the direction of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.

        A description of the direction.  # noqa: E501

        :param direction: The direction of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.  # noqa: E501
        :type direction: str
        """

        self._direction = direction

    @property
    def number(self):
        """Gets the number of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.  # noqa: E501

        Västtrafik service journey number that the trip leg is a part of.  # noqa: E501

        :return: The number of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.

        Västtrafik service journey number that the trip leg is a part of.  # noqa: E501

        :param number: The number of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.  # noqa: E501
        :type number: str
        """

        self._number = number

    @property
    def line(self):
        """Gets the line of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.  # noqa: E501


        :return: The line of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.  # noqa: E501
        :rtype: VTApiPlaneraResaWebV4ModelsJourneysLineApiModel
        """
        return self._line

    @line.setter
    def line(self, line):
        """Sets the line of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.


        :param line: The line of this VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel.  # noqa: E501
        :type line: VTApiPlaneraResaWebV4ModelsJourneysLineApiModel
        """

        self._line = line

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel):
            return True

        return self.to_dict() != other.to_dict()
