# coding: utf-8

"""
    Planera Resa

    Sök och planera resor med Västtrafik  # noqa: E501

    The version of the OpenAPI document: v4
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from pyvasttrafik.api.configuration import Configuration


class VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'details_reference': 'str',
        'service_journey': 'VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel',
        'stop_point': 'VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel',
        'planned_time': 'str',
        'estimated_time': 'str',
        'estimated_otherwise_planned_time': 'str',
        'is_cancelled': 'bool',
        'is_part_cancelled': 'bool'
    }

    attribute_map = {
        'details_reference': 'detailsReference',
        'service_journey': 'serviceJourney',
        'stop_point': 'stopPoint',
        'planned_time': 'plannedTime',
        'estimated_time': 'estimatedTime',
        'estimated_otherwise_planned_time': 'estimatedOtherwisePlannedTime',
        'is_cancelled': 'isCancelled',
        'is_part_cancelled': 'isPartCancelled'
    }

    def __init__(self, details_reference=None, service_journey=None, stop_point=None, planned_time=None, estimated_time=None, estimated_otherwise_planned_time=None, is_cancelled=None, is_part_cancelled=None, local_vars_configuration=None):  # noqa: E501
        """VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._details_reference = None
        self._service_journey = None
        self._stop_point = None
        self._planned_time = None
        self._estimated_time = None
        self._estimated_otherwise_planned_time = None
        self._is_cancelled = None
        self._is_part_cancelled = None
        self.discriminator = None

        self.details_reference = details_reference
        if service_journey is not None:
            self.service_journey = service_journey
        self.stop_point = stop_point
        self.planned_time = planned_time
        self.estimated_time = estimated_time
        self.estimated_otherwise_planned_time = estimated_otherwise_planned_time
        if is_cancelled is not None:
            self.is_cancelled = is_cancelled
        if is_part_cancelled is not None:
            self.is_part_cancelled = is_part_cancelled

    @property
    def details_reference(self):
        """Gets the details_reference of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501

        A reference that should be used when getting detailed information about the journey.  # noqa: E501

        :return: The details_reference of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :rtype: str
        """
        return self._details_reference

    @details_reference.setter
    def details_reference(self, details_reference):
        """Sets the details_reference of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.

        A reference that should be used when getting detailed information about the journey.  # noqa: E501

        :param details_reference: The details_reference of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :type details_reference: str
        """

        self._details_reference = details_reference

    @property
    def service_journey(self):
        """Gets the service_journey of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501


        :return: The service_journey of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :rtype: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel
        """
        return self._service_journey

    @service_journey.setter
    def service_journey(self, service_journey):
        """Sets the service_journey of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.


        :param service_journey: The service_journey of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :type service_journey: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel
        """

        self._service_journey = service_journey

    @property
    def stop_point(self):
        """Gets the stop_point of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501


        :return: The stop_point of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :rtype: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel
        """
        return self._stop_point

    @stop_point.setter
    def stop_point(self, stop_point):
        """Sets the stop_point of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.


        :param stop_point: The stop_point of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :type stop_point: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel
        """
        if self.local_vars_configuration.client_side_validation and stop_point is None:  # noqa: E501
            raise ValueError("Invalid value for `stop_point`, must not be `None`")  # noqa: E501

        self._stop_point = stop_point

    @property
    def planned_time(self):
        """Gets the planned_time of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501

        The planned time of the call in RFC 3339 format.  # noqa: E501

        :return: The planned_time of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :rtype: str
        """
        return self._planned_time

    @planned_time.setter
    def planned_time(self, planned_time):
        """Sets the planned_time of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.

        The planned time of the call in RFC 3339 format.  # noqa: E501

        :param planned_time: The planned_time of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :type planned_time: str
        """
        if self.local_vars_configuration.client_side_validation and planned_time is None:  # noqa: E501
            raise ValueError("Invalid value for `planned_time`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                planned_time is not None and len(planned_time) < 1):
            raise ValueError("Invalid value for `planned_time`, length must be greater than or equal to `1`")  # noqa: E501

        self._planned_time = planned_time

    @property
    def estimated_time(self):
        """Gets the estimated_time of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501

        The estimated time of the call in RFC 3339 format.  # noqa: E501

        :return: The estimated_time of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :rtype: str
        """
        return self._estimated_time

    @estimated_time.setter
    def estimated_time(self, estimated_time):
        """Sets the estimated_time of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.

        The estimated time of the call in RFC 3339 format.  # noqa: E501

        :param estimated_time: The estimated_time of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :type estimated_time: str
        """

        self._estimated_time = estimated_time

    @property
    def estimated_otherwise_planned_time(self):
        """Gets the estimated_otherwise_planned_time of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501

        The best known time of the call in RFC 3339 format. Is EstimatedTime if exists, otherwise PlannedTime.  # noqa: E501

        :return: The estimated_otherwise_planned_time of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :rtype: str
        """
        return self._estimated_otherwise_planned_time

    @estimated_otherwise_planned_time.setter
    def estimated_otherwise_planned_time(self, estimated_otherwise_planned_time):
        """Sets the estimated_otherwise_planned_time of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.

        The best known time of the call in RFC 3339 format. Is EstimatedTime if exists, otherwise PlannedTime.  # noqa: E501

        :param estimated_otherwise_planned_time: The estimated_otherwise_planned_time of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :type estimated_otherwise_planned_time: str
        """

        self._estimated_otherwise_planned_time = estimated_otherwise_planned_time

    @property
    def is_cancelled(self):
        """Gets the is_cancelled of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501

        Flag indicating if the departure or arrival is cancelled.  # noqa: E501

        :return: The is_cancelled of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :rtype: bool
        """
        return self._is_cancelled

    @is_cancelled.setter
    def is_cancelled(self, is_cancelled):
        """Sets the is_cancelled of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.

        Flag indicating if the departure or arrival is cancelled.  # noqa: E501

        :param is_cancelled: The is_cancelled of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :type is_cancelled: bool
        """

        self._is_cancelled = is_cancelled

    @property
    def is_part_cancelled(self):
        """Gets the is_part_cancelled of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501

        Flag indicating if the departure or arrival is partially cancelled.  # noqa: E501

        :return: The is_part_cancelled of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :rtype: bool
        """
        return self._is_part_cancelled

    @is_part_cancelled.setter
    def is_part_cancelled(self, is_part_cancelled):
        """Sets the is_part_cancelled of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.

        Flag indicating if the departure or arrival is partially cancelled.  # noqa: E501

        :param is_part_cancelled: The is_part_cancelled of this VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel.  # noqa: E501
        :type is_part_cancelled: bool
        """

        self._is_part_cancelled = is_part_cancelled

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel):
            return True

        return self.to_dict() != other.to_dict()
